// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl5VC32BabaQEEhJyFXZ8HWE9RFsMDew8',
    appId: '1:948846557868:web:0f31ceded5e0e410d97d09',
    messagingSenderId: '948846557868',
    projectId: 'apex-3fd0c',
    authDomain: 'apex-3fd0c.firebaseapp.com',
    storageBucket: 'apex-3fd0c.firebasestorage.app',
    measurementId: 'G-2LXJBH4RZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrkjg6GhjefmYEjUtlDCZen4gOdxljn9w',
    appId: '1:948846557868:android:42d2eb97e218d12ed97d09',
    messagingSenderId: '948846557868',
    projectId: 'apex-3fd0c',
    storageBucket: 'apex-3fd0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt344Xp35sKkPLeaTRKKQdvuygaBYJF-o',
    appId: '1:948846557868:ios:19624e856e5237e1d97d09',
    messagingSenderId: '948846557868',
    projectId: 'apex-3fd0c',
    storageBucket: 'apex-3fd0c.firebasestorage.app',
    iosBundleId: 'com.example.apex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt344Xp35sKkPLeaTRKKQdvuygaBYJF-o',
    appId: '1:948846557868:ios:19624e856e5237e1d97d09',
    messagingSenderId: '948846557868',
    projectId: 'apex-3fd0c',
    storageBucket: 'apex-3fd0c.firebasestorage.app',
    iosBundleId: 'com.example.apex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl5VC32BabaQEEhJyFXZ8HWE9RFsMDew8',
    appId: '1:948846557868:web:8c8e4e2d31076705d97d09',
    messagingSenderId: '948846557868',
    projectId: 'apex-3fd0c',
    authDomain: 'apex-3fd0c.firebaseapp.com',
    storageBucket: 'apex-3fd0c.firebasestorage.app',
    measurementId: 'G-2X04PZXMP9',
  );
}